-
      name : 22talks
      url : http://22talks.com
      cvs: ''
      description: "22talks is a simple backoffice software to mantain the info in an event (or all of them) 
      your asociation manages.\n Using no more than 3 configuration steps, you can add/edit/delete all those
       events and their related speakers (their talks contents etc), sponsors and so on.\n 
       With all this data, we build your events landing page and launch it so anybody can attend."
      authors:
         - {name: "Fran Mosteiro", twitter: "https://twitter.com/fran_mosteiro", linkedin: "https://www.linkedin.com/in/franmosteiro/", github: "https://github.com/franmosteiro"}
         - {name: "Asier Marqués", twitter: "https://twitter.com/asiermarques", linkedin: "https://www.linkedin.com/in/asier/", github: "https://github.com/asiermarques"}

-
      name : MrCoyote
      url : http://mrcoyote.com
      cvs: ''
      description: "MrCoyote is a Search as a Service platform designed for developers and MVP projects."
      authors:
         - {name: "Mario Nunes", twitter: "https://twitter.com/mariotux", linkedin: "https://www.linkedin.com/in/mario-nunes/", github: "https://github.com/mariotux"}
         - {name: "Asier Marqués", twitter: "https://twitter.com/asiermarques", linkedin: "https://www.linkedin.com/in/asier/", github: "https://github.com/asiermarques"}